=== vbigiani/anoki-senior-java-challenge/src/test/resources/it/techgap/challenge/java/senior/schema.dtd
<!ELEMENT dataset (
    EMPLOYEE*)>

<!ELEMENT EMPLOYEE EMPTY>
<!ATTLIST EMPLOYEE
    CF CDATA #REQUIRED
    AGE CDATA #IMPLIED
    SALARY CDATA #IMPLIED
    MANAGER_CF CDATA #IMPLIED
>

=== vbigiani/anoki-senior-java-challenge/src/test/resources/it/techgap/challenge/java/senior/challenge-sql-dataset.xml
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE dataset SYSTEM "src/test/resources/it/techgap/challenge/java/senior/schema.dtd">

<dataset>
    <EMPLOYEE CF="XXXXX00X00X000M" AGE="29" SALARY="30000"/>
    <EMPLOYEE CF="XXXXX00X00X001M" AGE="30" SALARY="45000"/>
    <EMPLOYEE CF="XXXXX00X00X002M" AGE="45" SALARY="50000"/>
    <EMPLOYEE CF="XXXXX00X00X003M" AGE="50" SALARY="17000"/>
    <EMPLOYEE CF="XXXXX00X00X004M" AGE="27" SALARY="28000"/>


    <EMPLOYEE CF="XXXXX00X00X001D" AGE="22" SALARY="30000" MANAGER_CF="XXXXX00X00X001M"/>
    <EMPLOYEE CF="XXXXX00X00X011D" AGE="22" SALARY="30000" MANAGER_CF="XXXXX00X00X001M"/>
    <EMPLOYEE CF="XXXXX00X00X021D" AGE="35" SALARY="19000" MANAGER_CF="XXXXX00X00X001M"/>
    <EMPLOYEE CF="XXXXX00X00X031D" AGE="35" SALARY="14000" MANAGER_CF="XXXXX00X00X001M"/>
    <EMPLOYEE CF="XXXXX00X00X041D" AGE="35" SALARY="17000" MANAGER_CF="XXXXX00X00X001M"/>
    <EMPLOYEE CF="XXXXX00X00X002D" AGE="29" SALARY="25000" MANAGER_CF="XXXXX00X00X002M"/>
    <EMPLOYEE CF="XXXXX00X00X004D" AGE="38" SALARY="35000" MANAGER_CF="XXXXX00X00X002M"/>
    <EMPLOYEE CF="XXXXX00X00X005D" AGE="42" SALARY="42000" MANAGER_CF="XXXXX00X00X003M"/>
    <EMPLOYEE CF="XXXXX00X00X006D" AGE="26" SALARY="28000" MANAGER_CF="XXXXX00X00X004M"/>
    <EMPLOYEE CF="XXXXX00X00X007D" AGE="50" SALARY="45000" MANAGER_CF="XXXXX00X00X004M"/>

</dataset>
